"""Add user roles: admin and member

Revision ID: 511ca9c9e030
Revises: b8476a4707fe
Create Date: 2021-10-01 16:02:32.991997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511ca9c9e030'
down_revision = 'b8476a4707fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='role'), server_default='MEMBER', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
