"""empty message

Revision ID: b8476a4707fe
Revises: 3e9a9ad8a00a
Create Date: 2021-09-30 12:23:48.468487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8476a4707fe'
down_revision = '3e9a9ad8a00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
