import json
import os

import typer

from api.main import app

typer_app = typer.Typer()


@typer_app.command()
def openapigen():
    """Generates an OpenApi file in api/autogenerated/openapi.json for our FastAPI application."""
    filename = "openapi.json"

    app.setup()

    schema_dict = app.openapi()
    if not schema_dict:
        typer.echo("Error: OpenAPI Schema is empty", err=True, color=True)
        return typer.Exit(1)

    # Create autogenerated directory
    curpath = os.path.abspath(os.curdir)
    gendir = os.path.join(curpath, "api", "autogenerated")
    if not os.path.exists(gendir):
        typer.echo(f"Creating new {gendir} directory")
        os.mkdir(gendir)

    filepath = os.path.join(gendir, filename)

    # Write schema to openapi.json
    with open(filepath, "w") as openapi_file:
        typer.echo(f"Writing OpenAPI schema to {filepath}")
        json.dump(schema_dict, openapi_file, indent=4)
        typer.echo("Complete")

    return typer.Exit(0)


if __name__ == "__main__":
    typer_app()
